version: '3'

services:
  digital-classroom:
    build: .
    restart: always
    ports:
      - 8085:8085
    environment:
      - BBB_UPSTREAM_SECRET
      - BBB_UPSTREAM_URI
      - BBB_ORIGIN_NAME
      - BBB_ORIGIN_VERSION
      - CLASSROOM_SECRET
      - CLASSROOM_URL
      - CLASSROOM_PORT
      - JWT_SECRET