version: '3'

services:
  digital-classroom:
    build: .
    restart: always
    ports:
      - 8085:8085
    environment:
      - BBB_UPSTREAM_URL
      - BBB_UPSTREAM_SECRET
      - CLASSROOM_SECRET
      - CLASSROOM_URL
      - CLASSROOM_PORT
      - JWT_SECRET
      - JWT_EXPIRATION