version: "3"

services:
  digital-classroom:
    build: .
    restart: always
    ports:
      - "8085:8085"
    environment:
      - CLASSROOM_BBB_UPSTREAM_URL
      - CLASSROOM_BBB_UPSTREAM_SECRET
      - CLASSROOM_SECRET
      - CLASSROOM_HOST
      - CLASSROOM_PREFIX_PATH
      - CLASSROOM_PORT
      - CLASSROOM_JWT_SECRET
      - CLASSROOM_JWT_EXPIRATION
      - CLASSROOM_KEYSTORE_PATH
      - CLASSROOM_KEYSTORE_PASS
      - CLASSROOM_LOGGING_LEVEL
  influx:
    image: influxdb:1.8.6
    ports:
      - "8086:8086"
    volumes:
      - ./../influxDB:/var/lib/influxdb
      - ./examples/influx/influx.conf:/etc/influxdb/influx.conf
    networks:
      - network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/lib:/var/lib/grafana
    networks:
      - network
networks:
  network:
    driver: bridge
