version: "3"

services:
  digital-classroom:
    build: .
    restart: always
    ports:
      - 8085:8085
    environment:
      - CLASSROOM_BBB_UPSTREAM_URL
      - CLASSROOM_BBB_UPSTREAM_SECRET
      - CLASSROOM_SECRET
      - CLASSROOM_HOST
      - CLASSROOM_PREFIX_PATH
      - CLASSROOM_PORT
      - CLASSROOM_JWT_SECRET
      - CLASSROOM_JWT_EXPIRATION
      - CLASSROOM_KEYSTORE_PATH
      - CLASSROOM_KEYSTORE_PASS
