openapi: 3.0.0
info:
  title: Digital Classroom Gateway API
  description: API to control the digital classroom application from the gateway service. This APi is based on the Big Blue Button API.
  version: 0.0.1

tags:
  - name: Create Room
    description: Creating a new digital classroom
servers:
  - url: 'https://localhost:8080/api/v1'
paths:
  /create:
    get:
      tags:
        - Create Room
      parameters:
        - in: query
          name: meetingID
        - in: query
          name: name
        - in: query
          name: welcome
        - in: query
          name: attendeePW
        - in: query
          name: moderatorPW
        - in: query
          name: checksum

      responses:
        "200":
          description: OK
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/create'
        "401":
          description: Unauthorized
  /join:
    get:
      tags:
        - Join a user to an existing classroom instance
      parameters:
        - in: query
          name: meetingID
        - in: query
          name: fullName
        - in: query
          name: password
        - in: query
          name: userID
        - in: query
          name: checksum

      responses:
        "200":
          description: OK
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/join'
        "401":
          description: Unauthorized

components:
  schemas:
    create:
      type: object
      description: Response structure for conference creation call
      properties:
        returncode:
          type: string
        meetingID:
          type: string
        internalMeetingID:
          type: string
        parentMeetingID:
          type: string
        attendeePW:
          type: string
        moderatorPW:
          type: string
        createTime:
          type: number
        voiceBridge:
          type: string
        dialNumber:
          type: string
        createDate:
          type: string
        hasUserJoined:
          type: boolean
        duration:
          type: number
        hasBeenForciblyEnded:
          type: boolean
        messageKey:
          type: string
        message:
          type: string

    join:
      type: object
      description: Response structure for conference user join
      properties:
        returncode:
          type: string
        messageKey:
          type: string
        message:
          type: string
        meeting_id:
          type: string
        user_id:
          type: string
        auth_token:
          type: string
        session_token:
          type: string
        url:
          type: string


