upstream:
  bbb:
    service-url: ${CLASSROOM_BBB_UPSTREAM_URL:https://fk-vv.mni.thm.de/bigbluebutton/api}
    shared-secret: ${CLASSROOM_BBB_UPSTREAM_SECRET:8Dsupersecurekeydf0}

classroom:
  shared-secret: ${CLASSROOM_SECRET:8Dsupersecurekeydf0}
  host: ${CLASSROOM_HOST:https://localhost:8085}
  prefix-path: ${CLASSROOM_PREFIX_PATH:}

server:
  ssl:
    enabled: ${CLASSROOM_SSL_ENABLED:true}
    key-store: ${CLASSROOM_KEYSTORE_PATH:classpath:keystore.p12}
    key-store-password: ${CLASSROOM_KEYSTORE_PASS:passwd}
    key-store-type: ${CLASSROOM_KEYSTORE_TYPE:PKCS12}
    client-auth: none
    protocol: "TLS"
  port: ${CLASSROOM_PORT:8085}

jwt:
  secret: ${CLASSROOM_JWT_SECRET:8Dsupersecurekeydf0}
  expiration: ${CLASSROOM_JWT_EXPIRATION:900}

logging:
  level:
    de.thm: DEBUG
    SQL: DEBUG
    org:
      springframework:
        web: DEBUG
        security:
          rsocket:
            core: DEBUG
        messaging:
          rsocket: DEBUG

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration
  web:
    resources.static-locations: classpath:static/
  webflux:
    static-path-pattern: /static/*
  rsocket:
    server:
      mapping-path: /rsocket
      transport: websocket
      ssl.enabled: true

