upstream:
  bbb:
    service-url: ${BBB_UPSTREAM_URL:https://fk-vv.mni.thm.de/bigbluebutton/api}
    shared-secret: ${BBB_UPSTREAM_SECRET:8Dsupersecurekeydf0}

classroom:
  shared-secret: ${CLASSROOM_SECRET:8Dsupersecurekeydf0}
  url: ${CLASSROOM_URL:http://localhost}

server.port: ${CLASSROOM_PORT:8085}

jwt:
  secret: ${JWT_SECRET:8Dsupersecurekeydf0}
  expiration: ${JWT_EXPIRATION:900}

logging:
  level:
    de.thm: DEBUG
    SQL: DEBUG
    web: DEBUG

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration, org.springframework.boot.autoconfigure.security.rsocket.RSocketSecurityAutoConfiguration
  web:
    resources.static-locations: classpath:static/
  webflux:
    static-path-pattern: /static/*
