version: '3'

services:
  digital-classroom:
    image: thmmniii/digital-classroom:latest
    restart: always
    environment:
      - BBB_UPSTREAM_URL
      - BBB_UPSTREAM_SECRET
      - CLASSROOM_SECRET
      - CLASSROOM_HOST
      - CLASSROOM_PREFIX_PATH
      - CLASSROOM_PORT
      - JWT_SECRET
      - JWT_EXPIRATION