name: Release CI

on:
  push:
    tags: ["v*.*.*"]

jobs:
  deploy:
    name: Create a Release
    runs-on: ubuntu-latest

    steps:
      - name: Get the Tag version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          futureRelease: ${{ steps.get_version.outputs.version }}
          onlyLastTag: true
          stripGeneratorNotice: true
          pullRequests: false
          enhancementLabels: ""
          issuesLabel: "**Changes:**"
          addSections: '{"internal": { "prefix": "**Internal:**", "labels": ["CI/CD"] }}'
      - name: Release
        uses: softprops/action-gh-release@v0.1.13
        with:
          body: steps.changelog.outputs.changelog
          prerelease: ${{ startsWith(github.ref, 'refs/tags/v0') || contains(github.ref, fromJson('["beta", "alpha"]')) }}
