name: Release CI

on:
  push:
    tags: ["v*.*.*"]

jobs:
  deploy:
    name: Create a Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v0.1.13
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ startsWith(github.ref, 'refs/tags/v0') || contains(github.ref, fromJson('["beta", "alpha"]')) }}
          generate_release_notes: true
